# 项目启动端口
server:
  port: 8080
# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.0.216:3306/family_service_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: xtfvmtd198154
    deiver-class-name: com.mysql.cj.jdbc.Driver
#配置mybatis
  mapper-locations: classpath:com/zxf/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  levle:
    com:
      zxf:
        mapper: debug
