server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #用于集群时候的服务器名称
  # hostname: localhost #eureka服务器实例名称--单服务器时候
  client:
    register-with-eureka: false # false 表示不像注册中心注册自己
    fetch-registry: false  # 自己是注册中心，我的职责就是维护服务实例，并不需要检索服务。
    service-url:
      #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单服务器
       defaultZone: http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka
  server:
     #关闭自我保护机制，保证不可用服务被及时剔除。
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000 #2000毫秒,服务器在2000毫秒内没有发现某些宕机或者出现问题的服务及时给与剔除。